### ISSUE TITLE
Has support with minify:true and mangle:true

### ISSUE THREAD

**Issue by delagen** [tengyifei/systemjs-bundle-minify#1]
When minify:true and mangle:true
does not work

**Comment by Delagen** [comment]
Seem to 
```
callExpr.callee.object.name === 'System'
```
issue

**Comment by Delagen** [comment]
Temporary avoid this with own uglify call

**Comment by tengyifei** [comment]
The SystemJS built-in minifier mangles function parameters, making it difficult to identify the app entry point. I'll see if I can make the code adapt to that.

**Comment by Delagen** [comment]
I think that SystemJS has plugin support. May be to support this through plugin? But may be not $)

**Comment by tengyifei** [comment]
Fixed via 2e0a2a0b53d567e17c5bf86c255b3030bdccce86

**Comment by tengyifei** [comment]
Yes SystemJS has plugins. But this is to be used with SystemJS builder, which is another tool all together. I don't think it has any sort of plugin support.
